/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Main */

#ifndef _Included_main_Main
#define _Included_main_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Main
 * Method:    isPalindrome
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_main_Main_isPalindrome
  (JNIEnv *, jclass, jstring);

/*
 * Class:     main_Main
 * Method:    withoutDuplicates
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_main_Main_withoutDuplicates
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     main_Main
 * Method:    chunk
 * Signature: (Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_main_Main_chunk
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     main_Main
 * Method:    greeter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_Main_greeter
  (JNIEnv *, jclass);

/*
 * Class:     main_Main
 * Method:    reversed
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_main_Main_reversed
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
